server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能
#          lower-case-service-id: true
      routes:
        - id: payment_routh     #路由的id，没有固定规则，但要求统一，建议配合服务名
#          uri: http://localhost:8001  #配置后提供服务的路由地址
          uri: lb://cloud-payment-service #此处如果有问题，请注意依赖spring-cloud-starter-netflix-eureka-client依赖不能错
          predicates:
            - Path=/payment/get/**         #断言，路径相匹配的进行路由
#           - After=2020-05-25T15:36:47.727+08:00[Asia/Shanghai]  #在这个时间后，该路由配置才生效
#           - Cookie=username,zzyy #携带cookie才生效
#          filters:
#            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id值为1024
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**